"""scout timeline + contradictions

Revision ID: 2460d638860e
Revises: b8469d3e03ae
Create Date: 2026-08-30 09:20:41.569984

Scout Elevated V2 PR2. scout_contradictions is a direct client_id table,
same tenant_isolation shape as consent_receipts / scout_interview_sessions.
timeline_json gets a server default so the NOT NULL add doesn't choke on
any pre-existing session rows.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2460d638860e'
down_revision: Union[str, Sequence[str], None] = 'b8469d3e03ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scout_contradictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=200), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('founder_session_id', sa.Integer(), nullable=False),
    sa.Column('sme_session_id', sa.Integer(), nullable=False),
    sa.Column('founder_text', sa.Text(), nullable=False),
    sa.Column('sme_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', name='contradictionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['founder_session_id'], ['scout_interview_sessions.id'], ),
    sa.ForeignKeyConstraint(['sme_session_id'], ['scout_interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scout_contradictions_client', 'scout_contradictions', ['client_id'], unique=False)
    op.add_column(
        'scout_interview_sessions',
        sa.Column('timeline_json', sa.Text(), nullable=False, server_default='{}'),
    )
    # ### end Alembic commands ###

    current_client = "NULLIF(current_setting('app.current_client_id', true), '')::integer"
    op.execute("ALTER TABLE scout_contradictions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE scout_contradictions FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON scout_contradictions FOR ALL "
        f"USING (client_id = {current_client}) "
        f"WITH CHECK (client_id = {current_client})"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON scout_contradictions")
    op.execute("ALTER TABLE scout_contradictions NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE scout_contradictions DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scout_interview_sessions', 'timeline_json')
    op.drop_index('ix_scout_contradictions_client', table_name='scout_contradictions')
    op.drop_table('scout_contradictions')
    # ### end Alembic commands ###
