"""ratifications table

Revision ID: 69290a7410da
Revises: ee6982ff21fb
Create Date: 2026-08-28 08:00:04.517293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69290a7410da'
down_revision: Union[str, Sequence[str], None] = 'ee6982ff21fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('work_unit_id', sa.Integer(), nullable=False),
    sa.Column('business_object', sa.String(length=200), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('ratified_by', sa.String(length=120), nullable=False),
    sa.Column('ratified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['genome_versions.id'], ),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'work_unit_id', name='uq_ratifications_version_wu')
    )
    # ### end Alembic commands ###

    # RLS, same pattern as every other tenant-scoped table (see 9a07306c5434).
    op.execute("ALTER TABLE ratifications ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ratifications FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON ratifications FOR ALL "
        "USING (client_id = NULLIF(current_setting('app.current_client_id', true), '')::integer) "
        "WITH CHECK (client_id = NULLIF(current_setting('app.current_client_id', true), '')::integer)"
    )
    # wep_app default privileges already cover future tables created by wep
    # (see f198c4aadd2c), but grant explicitly here too since this table
    # didn't exist when that ALTER DEFAULT PRIVILEGES ran.
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ratifications TO wep_app")
    op.execute("GRANT USAGE, SELECT ON ratifications_id_seq TO wep_app")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON ratifications")
    op.execute("ALTER TABLE ratifications NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ratifications DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratifications')
    # ### end Alembic commands ###
