"""consent receipts revoke/purge timestamps + indexes

Revision ID: 7079a0181dc8
Revises: c1d2e3f4a5b6
Create Date: 2026-08-29 08:34:25.804598

Slice 3 PR 3c: consent_receipts.status (P0) records whether a receipt left
the active state but not when — POST /consent/receipts/{id}/revoke and the
daily purge_expired_consents() job both need a timestamp to write. Two
composite indexes back the purge job's WHERE client_id = ... AND
auto_purge_at < now() scan and the subject-lookup path (GET by subject),
mirroring org_api_keys.expires_at's grace-window index from PR 3a.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7079a0181dc8'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent_receipts', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('consent_receipts', sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_consent_receipts_client_expiry', 'consent_receipts', ['client_id', 'auto_purge_at'], unique=False)
    op.create_index('ix_consent_receipts_client_subject', 'consent_receipts', ['client_id', 'interview_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_consent_receipts_client_subject', table_name='consent_receipts')
    op.drop_index('ix_consent_receipts_client_expiry', table_name='consent_receipts')
    op.drop_column('consent_receipts', 'purged_at')
    op.drop_column('consent_receipts', 'revoked_at')
    # ### end Alembic commands ###
