"""automation index: volume_per_month + edge reason/detection_method

Revision ID: 8ba56adb6720
Revises: 69290a7410da
Create Date: 2026-08-28 03:09:35.592934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba56adb6720'
down_revision: Union[str, Sequence[str], None] = '69290a7410da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (Sequence edges from prior
    # imports); the ORM-side default="" only applies to new inserts.
    op.add_column('work_edges', sa.Column('reason', sa.Text(), nullable=False, server_default=''))
    op.add_column('work_edges', sa.Column('detection_method', sa.String(length=60), nullable=False, server_default=''))
    op.add_column('work_units', sa.Column('volume_per_month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_units', 'volume_per_month')
    op.drop_column('work_edges', 'detection_method')
    op.drop_column('work_edges', 'reason')
    # ### end Alembic commands ###
