"""baseline schema from create_all plus P0 foundation tables

Revision ID: b60fef9c9a01
Revises: 
Create Date: 2026-08-25 18:35:52.694910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60fef9c9a01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('entity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('business_object', 'actor', 'capability', 'resource', 'policy', 'state', name='entitykind'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('state_machine', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regulatory_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regulation', sa.String(length=200), nullable=False),
    sa.Column('clause', sa.String(length=200), nullable=False),
    sa.Column('control_objective', sa.Text(), nullable=False),
    sa.Column('requires_licensed_human', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trace_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('log', 'email', 'ticket', 'transcript', 'erp_event', 'process_mining', 'interview', 'shadowing', name='tracekind'), nullable=False),
    sa.Column('object_ref', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance', sa.Enum('observed', 'declared', 'inferred', 'designed', name='provenance'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('interview_ref', sa.String(length=200), nullable=False),
    sa.Column('data_principal_initials', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('withdrawal_method', sa.String(length=200), nullable=False),
    sa.Column('auto_purge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'withdrawn', 'purged', name='consentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('external_ref', sa.String(length=200), nullable=False),
    sa.Column('current_state', sa.String(length=80), nullable=False),
    sa.Column('provenance', sa.Enum('observed', 'declared', 'inferred', 'designed', name='provenance', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['entity_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genome_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('version_type', sa.Enum('inferred', 'detailed', 'ratified', name='genomeversiontype'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('gqs_score', sa.Integer(), nullable=True),
    sa.Column('work_unit_count', sa.Integer(), nullable=False),
    sa.Column('gates_passed', sa.Text(), nullable=False),
    sa.Column('gates_failed', sa.Text(), nullable=False),
    sa.Column('changes_summary', sa.Text(), nullable=False),
    sa.Column('ratified', sa.Boolean(), nullable=False),
    sa.Column('ratified_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intent_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('policy', 'sop', 'okr', 'regulation', 'job_description', 'contract', name='intentkind'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('provenance', sa.Enum('observed', 'declared', 'inferred', 'designed', name='provenance', create_type=False), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=120), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('business_object_type_id', sa.Integer(), nullable=False),
    sa.Column('current_condition', sa.String(length=80), nullable=False),
    sa.Column('desired_condition', sa.String(length=80), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('inputs', sa.Text(), nullable=False),
    sa.Column('authority', sa.Text(), nullable=False),
    sa.Column('actor_constraints', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), nullable=False),
    sa.Column('evidence_required', sa.Text(), nullable=False),
    sa.Column('verification_method', sa.Enum('deterministic_rule', 'database_constraint', 'cross_system_reconciliation', 'human_spot_check', 'llm_as_judge', 'outcome_delay', 'counterparty_confirmation', name='verificationmethod'), nullable=False),
    sa.Column('sla_hours', sa.Float(), nullable=False),
    sa.Column('failure_semantics', sa.Text(), nullable=False),
    sa.Column('regulatory_entry_id', sa.Integer(), nullable=True),
    sa.Column('provenance', sa.Enum('observed', 'declared', 'inferred', 'designed', name='provenance', create_type=False), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('actor_type', sa.Enum('human', 'agent', 'deterministic', 'external', name='actortype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'reconciled', 'authoritative', name='unitstatus'), nullable=False),
    sa.Column('autonomy_level', sa.Integer(), nullable=False),
    sa.Column('is_sustaining', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_object_type_id'], ['entity_types.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['regulatory_entry_id'], ['regulatory_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'code', name='uq_work_units_client_code')
    )
    op.create_table('autonomy_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_unit_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('promotion', 'demotion', name='changekind'), nullable=False),
    sa.Column('from_level', sa.Integer(), nullable=False),
    sa.Column('to_level', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conformance_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('shadow_process', 'policy_violation', 'missing_acceptance', 'workaround', 'undeclared', 'unimplemented', name='gapkind'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('discovered_ref', sa.String(length=200), nullable=False),
    sa.Column('declared_ref', sa.String(length=200), nullable=False),
    sa.Column('work_unit_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_unit_id', sa.Integer(), nullable=False),
    sa.Column('executions_per_month', sa.Float(), nullable=False),
    sa.Column('minutes_per_execution', sa.Float(), nullable=False),
    sa.Column('verification_minutes', sa.Float(), nullable=False),
    sa.Column('failure_rate', sa.Float(), nullable=False),
    sa.Column('exception_minutes', sa.Float(), nullable=False),
    sa.Column('maintenance_hours', sa.Float(), nullable=False),
    sa.Column('attribution_confidence', sa.Float(), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_unit_id')
    )
    op.create_table('discovery_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('origin', sa.Enum('upward', 'downward', name='origin'), nullable=False),
    sa.Column('provenance', sa.Enum('observed', 'declared', 'inferred', 'designed', name='provenance', create_type=False), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('sampling_bias_note', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('new', 'merged', 'rejected', name='candidatestatus'), nullable=False),
    sa.Column('work_unit_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.Enum('semantic', 'structural', name='relationkind'), nullable=False),
    sa.Column('provenance', sa.Enum('observed', 'declared', 'inferred', 'designed', name='provenance', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pii_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_unit_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=60), nullable=False),
    sa.Column('pii_type', sa.String(length=30), nullable=False),
    sa.Column('encrypted_value', sa.LargeBinary(), nullable=False),
    sa.Column('redacted_preview', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('row_ref', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'resolved', 'rejected', name='reviewqueuestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spec_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_unit_id', sa.Integer(), nullable=False),
    sa.Column('check_type', sa.Enum('authority', 'evidence', 'condition', 'acceptance', name='checktype'), nullable=False),
    sa.Column('result', sa.Enum('allowed', 'denied', name='speccheckresult'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('caller', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trajectories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_unit_id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.Enum('human', 'agent', 'deterministic', 'external', name='actortype', create_type=False), nullable=False),
    sa.Column('actor_ref', sa.String(length=120), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('llm_judge_score', sa.Float(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verdict_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_unit_id', sa.Integer(), nullable=False),
    sa.Column('verifiability', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.Integer(), nullable=False),
    sa.Column('reversibility', sa.Integer(), nullable=False),
    sa.Column('determinism', sa.Integer(), nullable=False),
    sa.Column('impact_scope', sa.Integer(), nullable=False),
    sa.Column('compliance', sa.Integer(), nullable=False),
    sa.Column('tacitness', sa.Integer(), nullable=False),
    sa.Column('recommended_level', sa.Integer(), nullable=False),
    sa.Column('applied_gates', sa.Text(), nullable=False),
    sa.Column('allocation', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_unit_id')
    )
    op.create_table('verification_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_unit_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('deterministic_rule', 'database_constraint', 'cross_system_reconciliation', 'human_spot_check', 'llm_as_judge', 'outcome_delay', 'counterparty_confirmation', name='verificationmethod', create_type=False), nullable=False),
    sa.Column('independent', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.Enum('passed', 'failed', 'inconclusive', name='verificationoutcome'), nullable=False),
    sa.Column('evidence_ref', sa.String(length=200), nullable=False),
    sa.Column('actor_ref', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('edge_type', sa.Enum('sequence', 'shared_object', 'shared_resource', 'reciprocal', name='edgetype'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['work_units.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['work_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_unit_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_unit_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('observed', 'declared', 'inferred', 'designed', name='provenance', create_type=False), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('row_ref', sa.Integer(), nullable=True),
    sa.Column('col_ref', sa.String(length=120), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_ref', sa.String(length=200), nullable=False),
    sa.Column('consent_receipt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consent_receipt_id'], ['consent_receipts.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_unit_id')
    )
    op.create_table('work_unit_regulatory_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_unit_id', sa.Integer(), nullable=False),
    sa.Column('regulatory_entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['regulatory_entry_id'], ['regulatory_entries.id'], ),
    sa.ForeignKeyConstraint(['work_unit_id'], ['work_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_unit_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('overrides', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['work_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_unit_variants')
    op.drop_table('work_unit_regulatory_links')
    op.drop_table('work_unit_provenance')
    op.drop_table('work_edges')
    op.drop_table('verification_runs')
    op.drop_table('verdict_scores')
    op.drop_table('trajectories')
    op.drop_table('spec_checks')
    op.drop_table('review_queue')
    op.drop_table('pii_field_values')
    op.drop_table('entity_edges')
    op.drop_table('discovery_candidates')
    op.drop_table('cost_profiles')
    op.drop_table('conformance_gaps')
    op.drop_table('autonomy_changes')
    op.drop_table('work_units')
    op.drop_table('uploaded_files')
    op.drop_table('org_api_keys')
    op.drop_table('intent_sources')
    op.drop_table('genome_versions')
    op.drop_table('entities')
    op.drop_table('consent_receipts')
    op.drop_table('audit_logs')
    op.drop_table('trace_events')
    op.drop_table('regulatory_entries')
    op.drop_table('entity_types')
    op.drop_table('clients')
    # ### end Alembic commands ###
