"""scout interview sessions + captured units

Revision ID: b8469d3e03ae
Revises: 7079a0181dc8
Create Date: 2026-08-30 05:09:59.361573

Scout Elevated V2 PR1. scout_interview_sessions is a direct client_id
table, same tenant_isolation policy shape as consent_receipts
(9a07306c5434). scout_captured_units has no client_id-independent
existence -- it's scoped through session_id -> scout_interview_sessions
.client_id, same WORK_UNIT_CHILD_TABLES pattern as work_unit_provenance
et al. (it also carries its own client_id column for query convenience,
but RLS keys off session_id to guarantee it can never point at a
session it doesn't belong to).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8469d3e03ae'
down_revision: Union[str, Sequence[str], None] = '7079a0181dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scout_interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('founder', 'sme', name='interviewtype'), nullable=False),
    sa.Column('interviewee_name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', name='interviewstatus'), nullable=False),
    sa.Column('completeness_pct', sa.Float(), nullable=False),
    sa.Column('consent_receipt_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['consent_receipt_id'], ['consent_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scout_sessions_client', 'scout_interview_sessions', ['client_id'], unique=False)
    op.create_table('scout_captured_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('inputs', sa.Text(), nullable=False),
    sa.Column('outputs', sa.Text(), nullable=False),
    sa.Column('systems', sa.String(length=300), nullable=False),
    sa.Column('frequency', sa.String(length=120), nullable=False),
    sa.Column('time_minutes', sa.Float(), nullable=True),
    sa.Column('pain', sa.Text(), nullable=False),
    sa.Column('handoffs', sa.String(length=200), nullable=False),
    sa.Column('decision_rule', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['scout_interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scout_units_session', 'scout_captured_units', ['session_id'], unique=False)
    # ### end Alembic commands ###

    current_client = "NULLIF(current_setting('app.current_client_id', true), '')::integer"

    op.execute("ALTER TABLE scout_interview_sessions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE scout_interview_sessions FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON scout_interview_sessions FOR ALL "
        f"USING (client_id = {current_client}) "
        f"WITH CHECK (client_id = {current_client})"
    )

    op.execute("ALTER TABLE scout_captured_units ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE scout_captured_units FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON scout_captured_units FOR ALL "
        "USING (session_id IN (SELECT id FROM scout_interview_sessions "
        f"WHERE client_id = {current_client})) "
        "WITH CHECK (session_id IN (SELECT id FROM scout_interview_sessions "
        f"WHERE client_id = {current_client}))"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON scout_captured_units")
    op.execute("ALTER TABLE scout_captured_units NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE scout_captured_units DISABLE ROW LEVEL SECURITY")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON scout_interview_sessions")
    op.execute("ALTER TABLE scout_interview_sessions NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE scout_interview_sessions DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scout_units_session', table_name='scout_captured_units')
    op.drop_table('scout_captured_units')
    op.drop_index('ix_scout_sessions_client', table_name='scout_interview_sessions')
    op.drop_table('scout_interview_sessions')
    # ### end Alembic commands ###
