"""add work_units.genome_version_id

Revision ID: d4d8503867c8
Revises: f198c4aadd2c
Create Date: 2026-08-25 20:55:27.927764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d8503867c8'
down_revision: Union[str, Sequence[str], None] = 'f198c4aadd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_units', sa.Column('genome_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'work_units', 'genome_versions', ['genome_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_units', type_='foreignkey')
    op.drop_column('work_units', 'genome_version_id')
    # ### end Alembic commands ###
