"""uploaded_files content, review_queue col+raw_text, fix confidence and gqs_score float type

Revision ID: ee6982ff21fb
Revises: d4d8503867c8
Create Date: 2026-08-27 14:54:30.252211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6982ff21fb'
down_revision: Union[str, Sequence[str], None] = 'd4d8503867c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('genome_versions', 'gqs_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('review_queue', sa.Column('col_ref', sa.String(length=120), nullable=False))
    op.add_column('review_queue', sa.Column('raw_text', sa.Text(), nullable=False))
    op.alter_column('review_queue', 'confidence',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('uploaded_files', sa.Column('content', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'content')
    op.alter_column('review_queue', 'confidence',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('review_queue', 'raw_text')
    op.drop_column('review_queue', 'col_ref')
    op.alter_column('genome_versions', 'gqs_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
