"""users table for Track 4 login scaffolding

Revision ID: efc855b7d06a
Revises: 68c3926e1143
Create Date: 2026-09-05 19:09:19.620477

Schema only (docs/ROADMAP-DECISIONS.md Track 4). Nothing reads or writes
this table yet -- no router, no session, no provider wired. RLS from the
start, same tenant_isolation shape as every other tenant table, with the
app.system_bypass clause already baked in (see 68c3926e1143) rather than
added in a follow-up migration once something forgets it needs one.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc855b7d06a'
down_revision: Union[str, Sequence[str], None] = '68c3926e1143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CURRENT_CLIENT = "NULLIF(current_setting('app.current_client_id', true), '')::integer"
SYSTEM_BYPASS = "current_setting('app.system_bypass', true) = 'on'"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='appuserrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', name='uq_users_external_id')
    )
    # ### end Alembic commands ###

    # wep_app's default privileges (f198c4aadd2c) already cover future tables
    # created by wep, same as 69290a7410da's own comment on this -- explicit
    # anyway, matching that migration's belt-and-suspenders convention.
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON users TO wep_app")
    op.execute("GRANT USAGE, SELECT ON users_id_seq TO wep_app")

    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE users FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON users FOR ALL "
        f"USING (client_id = {CURRENT_CLIENT} OR {SYSTEM_BYPASS}) "
        f"WITH CHECK (client_id = {CURRENT_CLIENT} OR {SYSTEM_BYPASS})"
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON users")
    op.execute("ALTER TABLE users NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE users DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
