export const GLOSSARY: Record<string, { simple: string; technical: string; example: string }> = {
  "Work Unit": { simple: "One small piece of work that has a clear start and finish.", technical: "Atomic unit of work with 18 contract attributes including authority, acceptance, evidence, verification.", example: "WU-ONB-04 Pre-Joining Communication" },
  "Ontology": { simple: "List of things we work on, like Employee, Offer, Asset.", technical: "Defines business objects and their states and allowed transitions.", example: "Employee with states draft -> pre_joining -> active" },
  "Business Object": { simple: "The thing this work acts on.", technical: "Entity type in ontology that work unit mutates.", example: "Employee" },
  "Authority / Owner": { simple: "Who is allowed to say this work is OK?", technical: "Role or system that must approve or be presented for execution.", example: "HR Ops SPOC" },
  "Owner Type": { simple: "Is this work done by human, robot, or automatic rule?", technical: "human | agent | deterministic", example: "agent for email sending" },
  "Current Condition": { simple: "What must be true BEFORE we can start this work?", technical: "Pre-state predicate on business object.", example: "Offer status = signed in Zoho" },
  "Desired Condition": { simple: "What must be true AFTER work is done? Definition of DONE.", technical: "Post-state predicate.", example: "Welcome mail status = delivered" },
  "Acceptance Criteria": { simple: "How do we check it is really done?", technical: "Human-readable rule that verification uses.", example: "Outlook mail log exists AND Teams invite exists" },
  "Verification Method": { simple: "How do we prove it? Automatic check or human check?", technical: "deterministic_rule | human_spot_check | database_constraint etc.", example: "deterministic_rule" },
  "Evidence / Evidence Ref": { simple: "Proof that work happened. Like message ID or ticket number.", technical: "Reference that runtime must present for ALLOW.", example: "Outlook message ID + Teams invite ID" },
  "VERDICT": { simple: "7 questions that decide if a robot can do this safely. 1=hard, 5=easy.", technical: "Verifiability, Evidence, Reversibility, Determinism, Impact, Compliance, Tacitness", example: "5,5,5,5,4,5,5 = L6" },
  "V - Verifiability": { simple: "How easy to check if it was done right?", technical: "Can we verify outcome?", example: "Checking mail log is easy = 5" },
  "E - Evidence": { simple: "Is proof easy to get?", technical: "Evidence availability", example: "Outlook ID easy = 5" },
  "R - Reversibility": { simple: "Can we undo it if wrong?", technical: "Can we revert?", example: "Resend mail = easy to reverse = 5" },
  "D - Determinism": { simple: "Same input always gives same output?", technical: "Predictability", example: "Template mail = deterministic = 5" },
  "I - Impact scope": { simple: "What breaks if it's wrong? Small or big?", technical: "Blast radius", example: "Welcome mail wrong = small impact = 4" },
  "C - Compliance": { simple: "Any legal risk?", technical: "Regulatory risk", example: "No regulatory risk = 5" },
  "T - Tacitness": { simple: "Does it need human gut-feel?", technical: "Tacit knowledge needed", example: "Template mail needs no gut-feel = 5" },
  "MEAN": { simple: "Average of your 7 scores.", technical: "Sum of 7 / 7", example: "4.857" },
  "UNCAPPED L": { simple: "What L-level mean would give without hard rules.", technical: "Before gates", example: "6" },
  "CAPPED L": { simple: "Final L after hard safety gates.", technical: "After applying 4 gates", example: "6 = can automate" },
  "Gates": { simple: "Hard safety rules that block automation.", technical: "gate1_regulatory, gate2_reversibility, gate3_impact, gate4_no_evidence", example: "[] = no gates" },
  "Allocation": { simple: "Who should do this? make=human does, agent=robot does with human check, automate=robot fully, buy=external.", technical: "make | agent | automate | buy", example: "automate for welcome mail" },
  "Verification Run": { simple: "One time we ran this work and checked if it passed.", technical: "Record with result pass/fail and evidence_ref", example: "5 runs needed for promotion" },
  "Promotion": { simple: "Moving work to higher autonomy (L1->L2). Needs human approval and 5 passing runs. One level at a time for safety.", technical: "Human-gated, needs approved_by", example: "L1->L2" },
  "Economics": { simple: "How much time and money this work costs.", technical: "Do time, Verify time, Exception %, FTE calculation", example: "Do 2 mins x 50 hires = 100 mins" },
  "Spec API": { simple: "The door that bots call before doing work. If bot can't show proof, door says DENY.", technical: "Governance by construction via X-Spec-Key", example: "POST /api/spec/check" },
  "X-Spec-Key": { simple: "Secret key that lets your bot call the spec door.", technical: "Shared secret header", example: "dev-spec-key-change-me" },
  "Authority check": { simple: "Do you have the right approver?", technical: "Checks approver token matches owner", example: "Needs HR Ops SPOC" },
  "Evidence check": { simple: "Do you have proof?", technical: "Checks evidence_ref present", example: "Needs MSG-123" },
  "Condition check": { simple: "Is object ready to START?", technical: "Pre-state check", example: "Offer status = signed in Zoho" },
  "Acceptance check": { simple: "Is object DONE?", technical: "Post-state check", example: "Welcome mail status = delivered" },
  "Object State": { simple: "Current status of the thing we work on.", technical: "Value of business object state", example: "draft, signed, delivered" },
  "ALLOW / DENY": { simple: "Green = you can do work. Red = blocked, here's why and how to fix.", technical: "Spec API enforcement decision", example: "ALLOW" },
  "Bulk Upload Excel": { simple: "Upload many Work Units at once from HR_Work_Units_Bulk.xlsx template", technical: "Parses .xlsx rows and POSTs each to /api/work-units with X-Spec-Key. Duplicate codes are reported as already exists.", example: "Created 11, 1 already exists (WU-ONB-04)" },
};
